#!/bin/bash
# Exclude binary files
# Show line numbers
# Search recursively and follow symbolic links
# Exclude specific folders and files
grep -InR --no-messages \
    --exclude='*.min.*' \
    --exclude-dir='*.egg-info' \
    --exclude-dir=.git \
    --exclude-dir=.terraform \
    --exclude-dir=terraform.tfstate.d \
    "$@" *
