#!/bin/bash
# npm install -g uglify-js sass
MODULE_NAMES="$@"
for MODULE_NAME in ${MODULE_NAMES}; do
    ROOT_FOLDER=`python -c "import ${MODULE_NAME}; from os.path import abspath as a, dirname as d; print(d(d(a(${MODULE_NAME}.__file__))))"`
    PYTHON_FOLDER=${ROOT_FOLDER}/${MODULE_NAME}
    mkdir -p ${PYTHON_FOLDER}/assets
    # Regenerate script files
    SOURCE_PATH=${ROOT_FOLDER}/node_modules/${MODULE_NAME/_/-}/index.js
    TARGET_PATH=${PYTHON_FOLDER}/assets/part.min.js
    if [ -e ${SOURCE_PATH} ]; then
        echo ${TARGET_PATH}
        uglifyjs -m < ${SOURCE_PATH} > ${TARGET_PATH}
    fi
    # Regenerate style files
    SOURCE_FOLDER=${ROOT_FOLDER}/sass_modules
    SOURCE_PATH=${ROOT_FOLDER}/sass_modules/${MODULE_NAME/_/-}.scss
    TARGET_PATH=${PYTHON_FOLDER}/assets/part.min.css
    if [ -e ${SOURCE_PATH} ]; then
        echo ${TARGET_PATH}
        sass -I ${SOURCE_FOLDER} ${SOURCE_PATH} ${TARGET_PATH}
    fi
done
