#!/bin/bash
CONFIGURATION_PATHS="
.bash_profile
.bashrc
.ruff.toml
.tmux.conf
.vimrc
"

cd $(dirname "$0")

for X in $CONFIGURATION_PATHS; do
    cp $X ~
    echo 'cp '$X ~
done

if command -v dnf; then
    X=dnf
else
    X=apt
fi
command -v tmux || sudo $X install tmux -y
command -v vim || sudo $X install vim-enhanced -y
command -v git || sudo $X install git -y

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall &> /dev/null
