#!/bin/bash
CONFIGURATION_FOLDERS="
.jupyter
"
SCRIPT_PATHS="
clean
clean-notebooks
get-timestamps.py
git-status
grep-
make-password.py
update-projects
vimfind-
vimgrep-
"

mkdir ~/Experiments ~/Projects

SCRIPTS_FOLDER=~/.scripts
if [ ! -e $SCRIPTS_FOLDER ]; then
    mkdir $SCRIPTS_FOLDER
fi
cd $(dirname "$0")
for X in $SCRIPT_PATHS; do
    cp $X $SCRIPTS_FOLDER
    chmod a+x $SCRIPTS_FOLDER/$X
    echo 'cp '$X $SCRIPTS_FOLDER
done

for X in $CONFIGURATION_FOLDERS; do
    cp -r $X ~
    echo 'cp '$X ~
done

if [ -n "$1" ]; then
    ENV_NAME=`basename $1`
else
    ENV_NAME=crosscompute
fi
echo "Using ENV_NAME=$ENV_NAME"
ENV_FOLDER=~/.virtualenvs/$ENV_NAME
if [ ! -d $ENV_FOLDER ]; then
    python3 -m venv $ENV_FOLDER --system-site-packages
fi
sed "s/.virtualenvs\/crosscompute/.virtualenvs\/$ENV_NAME/" ~/.bashrc > ~/.bashrc_
mv ~/.bashrc_ ~/.bashrc

source ~/.bashrc
v
pip install -U pip wheel
pip install -U trash-cli
